version: '3.8'
services:
  client:
    build:
      context: ./client
    ports:
      - "3001:3001"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    environment:
      - NODE_ENV=development

  server:
    build:
      context: ./server
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
      - PORT=4000
      - CLIENT_URL=http://localhost:3001
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/formicary

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: formicary
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
