name: Deploy to VPS

on:
  push:
    branches:
      - main
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Client Dependencies
        run: |
          cd client
          npm ci

      - name: Build Client
        run: |
          cd client
          npm run build
        env:
          NODE_ENV: production

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: 104.251.216.17
          username: root
          password: ${{ secrets.VPS_ROOT_PASSWORD }}
          script: |
            cd /var/www/formicary-app
            
            # Pull latest changes
            git fetch --all
            git reset --hard origin/${{ github.ref_name }}
            
            # Run deployment script
            ./scripts/deploy.sh

      - name: Upload Client Build
        uses: appleboy/scp-action@master
        with:
          host: 104.251.216.17
          username: root
          password: ${{ secrets.VPS_ROOT_PASSWORD }}
          source: "client/dist/*"
          target: "/var/www/formicary-app/client/build"
          strip_components: 2
